# EBNF Grammar for the Geezer DSL
# Geezer is a domain-specific language used to organize a database of Linux packages
# Author: Chubak Bidpaa

geezer-dsl	::= { command-define | install-define | package-define | comment }

comment		::= ";;" info-text newline

install-define	::= "definst" "for" identifier '=' cmd-call ';'

cmd-call	::= '%' identifier [ args-list ]
args-list	::= shell-word { shell-word }

package-define  ::= "defpkg" identifier '=' info-list ';'

info-list       ::= info-single { '|' info-single }
info-single     ::= identifier ':' info-text newline

command-define  ::= "defcmd" identifier [ params-list ] '=' command-text ';'
params-list	::= shell-word { shell-word }

identifier	::= letter { letter | digit | '_' }

digit		::= '0' | '1' | '2' | ... | '7' | '8' | '9'
letter 		::= 'A' | 'B' | 'C' | ... | 'X' | 'Y' | 'Z'

newline		::= ? newline character ?
command		::= ? A shell command ?
shell-word	::= ? Any valid shell word ?
command-text    ::= ? Any text not containing semicolon ?
info-text	::= ? Any text not containing newline ?

